# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'mnist_784.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
      # Runs a command using the runners shell
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r text/requirements.txt
      - name: Run a Python script
        run: python test_mnist_784.py